config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'
  get    'login',  to: 'sessions#new'
  post   'login',  to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :categories
  resources :articles do
    resources :votes, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy
  validates :title, :text, :image, :user_id, :category_id, presence: true

  mount_uploader :image, ImageUploader
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles

  validates :name, :priority, presence: true, uniqueness: true

  scope :cate_priority, -> { order('priority desc') }

  scope :cate_priority, -> { order('priority desc') }

  scope :all_articles, ->(category_id) { where(id: category_id).includes(:articles) }

  def latest_article
    articles.order(created_at: :desc)
  end
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates :name, presence: true
  validates :password, presence: true, length: { minimum: 6, maximum: 255 }
  validates :email, presence: true,
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_many :articles
  has_many :votes, dependent: :destroy

  has_secure_password
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SessionsHelper

  def index
    @articles = Article.all
    @categories = Category.cate_priority
  end

  def new
    @article = current_user.articles.build
  end

  def show
    @article = fetch_article
  end

  def create
    @article = current_user.articles.build(article_params)

    if @article.save
      redirect_to(@article, notice: 'An article was created!')
    else
      render :new
    end
  end

  def update
    @article = fetch_article
    if @article.update(article_params)
      flash[:notice] = 'Article updated!'
      redirect_to @article
    else
      render :edit
    end
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image, :category_id)
  end

  def fetch_article
    Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user

  include SessionsHelper

  def index
    @categories = Category.all
    @articles = Article.all
  end

  def new
    @category = Category.new
  end

  def show
    @category = fetch_category
    @articles = @category.articles
  end

  def edit
    @category = fetch_category
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      redirect_to(@category, notice: 'Category created!')
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end

  def fetch_category
    Category.find(params[:id])
  end

  def logged_in_user
    redirect_to(login_path, notice: 'You need to login!') unless logged_in?
  end
end

app/controllers/nav_controller.rb
class NavController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      flash[:notice] = "Welcome back #{user.name} "
      redirect_to :root
    else
      flash[:notice] = 'Wrong email or password combination'
      redirect_to login_path
    end
  end

  def destroy
    log_out if logged_in?
    flash[:notice] = 'We hope to see you soon!'
    redirect_to :root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = fetch_user
    @articles = @user.articles
  end

  def edit
    @user = fetch_user
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice] = "Welcome to local life #{@user.name}!"
      redirect_to :root
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def fetch_user
    User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  include SessionsHelper

  def create
    @vote = current_user.votes.new(article_id: vote_params)
    @article = Article.find(params[:article_id])

    if @vote.save
      redirect_to(article_path(@article), notice: 'You voted this article.')
    else
      redirect_to(article_path(@article), notice: 'You cannot vote this article.')
    end
  end

  def destroy
    vote = Vote.find_by(user: current_user, article_id: vote_params)
    @article = Article.find(vote_params)
    if vote
      vote.destroy
      redirect_to(article_path(@article), notice: 'You unvoted this article.')
    else
      redirect_to(articles_path, notice: 'You cannot unvote article that you did not vote before.')
    end
  end

  private

  def vote_params
    params.require(:article_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def featured_article
    if Article.joins(:votes).group('article_id').count.first.nil?
      Article.first || flash[:notice] = 'No featured article to display!'
    else
      @feature_article_id = Article.joins(:votes).group('article_id').count.collect { |id, vote| [vote, id] }
      feature_article_top = @feature_article_id.max[1]
      Article.find(feature_article_top)
    end
  end

  def articles_exist
    article = featured_article
    if article.class == Article
      render 'if_not_nil', featured_article: article
    else
      render 'if_nil', featured_article: article
    end
  end

  def display_latest_articles(cate)
    if cate.articles.empty?

    else
      render 'partial_2', cate: cate
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def available_category(cate)
    if cate.articles.empty?

    else
      render 'available', cate: cate
    end
  end
end

app/helpers/nav_helper.rb
module NavHelper
  def display_signin
    link_to 'Sign in', login_path, class: 'nav-link' unless logged_in?
  end

  def display_register
    link_to 'Register', new_user_path, class: 'nav-link shift' unless logged_in?
  end

  def display_new_article
    link_to 'New Article', new_article_path, class: 'nav-link' if logged_in?
  end

  def display_current_user
    link_to current_user.name, user_path(current_user), class: 'nav-link' if logged_in?
  end

  def display_logout
    link_to 'Log out', logout_path, method: :delete, class: 'nav-link shift' if logged_in?
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    else
      @current_user = nil
    end
  end

  def logged_in?
    current_user
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def display_notice
    flash.notice if notice
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def vote_unvote(article)
    vote = Vote.find_by(article: article, user: current_user)
    if vote
      link_to('Unvote', article_vote_path(id: vote.id, article_id: article.id), method: :delete, class: 'votes')
    else
      link_to('Vote', article_votes_path(article_id: article.id), method: :post, class: 'votes')
    end
  end
end

app/views/articles/_article.html.erb
<div class="container-fluid">
    <div class="article-container d-flex flex-row-reverse">
        <% @user.articles.each do |article| %>
            <div class="art-test ">
                <div class="col-lg-6 category-box">
                    <h3 class="cate-title"><%= link_to article.title, article, class: 'title-color' %></h3>
                    <h3 class="art-author">written by <%= "#{ article.user.name }" %></h3>
                    <h3 class="art-text"><%= article.text %></h3>
                </div>
                <div class="col-lg-6 side-image">
                    <%= cl_image_tag article.image.url, width: '105%', height: '260px' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>

    <%= f.label :text %>
    <%= f.text_area :text, class: 'form-control' %>

    <%= f.label :category %>
    <%= f.select :category_id, Category.all.map { |c| [c.name, c.id] }, class: 'form-control' %>
    <br>
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>

    <%= f.submit yield(:text_button), class: 'btn btn-primary' %>

<% end %>

app/views/articles/_if_nil.html.erb
<!-- <h3><%= featured_article %></h3> -->

app/views/articles/_if_not_nil.html.erb
<%= cl_image_tag featured_article.image.url, height: '580px', width: '100%', class: 'all-images' %>
    <div class="featured_title_text">
    <h3 class="featured_article_title"><%= featured_article.title %></h3>
</div>

app/views/articles/_partial_1.html.erb
 flash[:notice] = "No Article created!"

app/views/articles/_partial_2.html.erb
<div class="col-lg-3 box">
    <h3 class="category-link"><%= link_to cate.name, cate, class: 'category' %></h3>
    <h3 class="content-title"><%= link_to cate.latest_article.first.title, cate, class: 'link-title' %></h3>
    <%= cl_image_tag cate.latest_article.first.image.url, height: "240", width: "334", class: 'all-images' %>
</div>

app/views/articles/index.html.erb
<div class="container-fluid overall-box">
    <div class="">
        <div class="col-lg-12 feature-cover">
           <%= articles_exist %>
        </div>
    </div>
    <div class="latest_article_box">
        <% @categories.each do |cate| %>
            <%= display_latest_articles(cate) %>
        <% end %>
    </div>
</div>

app/views/articles/new.html.erb
<%= provide(:text_button, 'Create') %>
<div class="container">
    <div class="row">
        <div class="col-lg-6 col-lg-offset-3 article-form">
            <h2 class="text-center new">New Article</h2>
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/articles/show.html.erb
<div class="container-fluid">
    <div class="row article-container">
        <div class="col-lg-6 side-image">
            <%= cl_image_tag @article.image.url, width: '103%', height: '368px' %>
        </div>
        <div class="col-lg-6 text-box">
            <h3 class="show-title"><%= @article.title %></h3>
            <h3 class="art-author written-by">written by: <%= @article.user.name %></h3>
            <h3 class="show-content"><%= @article.text %></h3>
            
            <div class="vote-button">
                <%= vote_unvote(@article) %> <%= "#{@article.votes.count}" %>
            </div>
            
        </div>
    </div>
    <br>
    <%= link_to 'Back', root_url %>
</div>

app/views/categories/_available.html.erb
<h3 class="category-link"><%= link_to cate.name, cate, class: 'category' %> <div class="count-color"><%= "#{cate.articles.count}" %></div></h3>
<h3 class="content-title"><%= cate.articles.take.title %></h3>
<%= cl_image_tag cate.articles.take.image.url, height: "240", width: "334", class: 'all-images' %>

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :priority %>
    <%= f.number_field :priority, class: 'form-control' %>

    <%= f.submit yield(:text_button), class: 'btn btn-primary catego' %>
<% end %>

app/views/categories/_not_available.html.erb
flash[:notice] = "No category to display article yet. But you can create one!"

app/views/categories/index.html.erb
<div class="container-fluid">
    <div class="all-categories">
        <% @categories.collect do |cate| %>
            <div class="col-lg-3 box">
               <%= available_category(cate) %>
            </div>
        <% end %>
    </div>
</div>

app/views/categories/new.html.erb
<%= provide(:text_button, 'Create') %>
<div class="container-fluid">
    <div class="row image-area">
        <div class="col-lg-12 new_cate_page">

        </div>
    </div>
    <div class="row">
        <div class="col-lg-4"></div>
        <div class="col-lg-4">
            <h2>Create New Category</h2>
            <%= render 'form' %>  
        </div>
        <div class="col-lg-4"></div>
    </div>
</div>

app/views/categories/show.html.erb
<div class="container-fluid">
    <h3 class="count-info">There are <%= "#{ @category.articles.count } #{ "article".pluralize(@category.articles.count) }" %> in <%= "#{ @category.name }" %> category</h3>
    <div class="article-container d-flex flex-row-reverse">
        <% @articles.each do |article| %>
            <div class="art-test ">
                <div class="col-lg-6 category-box">
                    <h3 class="cate-name"><%= @category.name %></h3>
                    <h3 class="cate-title"><%= link_to article.title, article, class: 'title-color' %></h3>
                    <h3 class="art-author">written by <%= "#{ article.user.name }" %></h3>
                    <h3 class="art-text"><%= article.text %></h3>
                </div>
                <div class="col-lg-6 side-image">
                    <%= cl_image_tag article.image.url, width: '105%', height: '260px' %>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="navbar-fixed-bottom navbar-expand-lg navbar-light">
  <div class="logo-like logo-bottom">
    <h3><%= link_to 'LiVe+LoCaL', '#', class: 'logo bottom-logo' %></h3>
    <div id="circle"></div>
  </div>
  <div>
    <p class="text-bottom">Copyright 2020. All rights reserved</p>
  </div>
  <div class="social-connect text-bottom">
    Connect with me:
    <%=link_to(content_tag(:i, nil, class: "fab fa-twitter-square social-icon fa-2x space"), "https://twitter.com/qoosim_ayinde", target: "_blank") %>
    <%=link_to(content_tag(:i, nil, class: "fab fa-github-square social-icon fa-2x space"), "https://github.com/Qoosim", target: "_blank") %>
    <%=link_to(content_tag(:i, nil, class: "fab fa-linkedin social-icon fa-2x space"), "https://www.linkedin.com/in/qoosim-abdulghaniyy-3609/", target: "_blank") %>   
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RorCapstone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="header">
      <%= render 'nav/nav' %>
    </div>

    <div class="message">
      <%= display_notice %>
    </div>

    <div class="main">
      <%= yield %>
    </div>

    <div class="footer">
      <%= render 'layouts/footer' %>
    </div>
    
  </body>
</html>

app/views/nav/_nav.html.erb
<nav class="navbar-fixed-top navbar-expand-lg navbar-light navigation", style="background: #ebd59b;">
    <div class="logo-like">
        <h3><%= link_to 'LiVe+LoCaL', root_path, class: 'logo' %></h3>
        <div id="circle"></div>
    </div>
    <ul class="nav navbar-nav">
        <li><%= link_to 'Add Category', new_category_path, class: 'nav-link' %></li>
        <li><%= link_to 'All Categories', categories_path, class: 'nav-link' %></li>
    </ul>
    <div>
        <ul class="nav navbar-nav navbar-right">
            <li><%= display_signin %></li>
            <li><%= display_register %></li>
            <li><%= display_new_article %></li>
            <li><%= display_current_user %></li>
            <li><%= display_logout%></li>
        </ul>
    </div>
</nav>

app/views/shared/_signup_form.html.erb
<div>
    <h2 class="signup">Sign up</h2>
    <%= form_for(@user) do |f| %>

        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.text_field :email, class: 'form-control' %>

        <%= f.label :password %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit yield(:text_button), class: 'btn btn-primary' %>

    <% end %>
<div>

app/views/users/index.html.erb
<%# <h1>List of Users</h1> %>

app/views/users/new.html.erb
<%= provide(:text_button, 'Sign up') %>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-6">
            <div class="col-lg-12 signup-image leftimg">
            </div>
        </div>
        <div class="col-lg-5 login-profile">
            <div class="row">
                <div class="col-lg-11">
                    <%= render 'shared/signup_form' %>
                </div>
                <div class="col-lg-1"></div>
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<div class="container-fluid">
    <h3 class="count-info">Hey <%= @user.name %>, you have <%= "#{ @articles.count } #{ "article".pluralize(@articles.count) }" %> created!</h3>
</div>

<div>
    <%= render 'articles/article' %>
</div>